version: '3.1'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./build/mysql:/var/lib/mysql
    restart: always
    hostname: mysql
    container_name: dbProject_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: hamidreza
      MYSQL_PASSWORD: shahriari
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
